spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost/springcloud_learning?serverTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=false